spring:
  profiles:
    active: prod

logging:
  level:
    com.shenzhou.service: debug
  file:
    name: log/springBootLog.log
mybatis:
  type-aliases-package: com.shenzhou.entity
  mapper-locations: classpath:mapper/*.xml

---
server:
  port: 9002

spring:
  profiles: prod

  application:
    name: automate-interface-service
  #配置数据源
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://10.10.22.108:1433;databaseName=BDDMS
    username: sa
    password: P@ssw0rd

---
server:
  port: 9000
spring:
  profiles: dev
  application:
    name: automate-interface-service
  #配置数据源
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://10.10.76.5:40201;databaseName=BDDMS
    username: SA
    password: P@ssw0rd
